let actionConstants  = () => {
	

	return {
		"SET_FLAGS" : "SET_FLAGS",
		"SET_CURRENT_GAME_BOARD" : "SET_CURRENT_GAME_BOARD",
		"UPDATE_CURRENT_GAME_BOARD" : "UPDATE_CURRENT_GAME_BOARD",
		"SET_NEW_GAME_BOARD" : "SET_NEW_GAME_BOARD",
		"SET_PREVIOUS_GAME_BOARD" : "SET_PREVIOUS_GAME_BOARD"
	};

};

export default actionConstants();